// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjhnakowlssfychhmexk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqaG5ha293bHNzZnljaGhtZXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDA4MDksImV4cCI6MjA1NTYxNjgwOX0.KoGkwsPrirchE8fqiToB-tw3NRDI1pWG6LcbPDiBlTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);